import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cat Facts App", // Update the title here
  description: "Description of your app",
  icons: {
    icon: "/images/logo.webp", // Path to your favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.webp" /> {/* Ensure the path is correct */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
